CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(150) NOT NULL,
                          description VARCHAR(500),
                          price DECIMAL(10,2) NOT NULL,
                          created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_products_name ON products(name);